### ISSUE TITLE
Bug: "Undefined index: email_format"

### ISSUE THREAD

**Issue by VeerPrince** [Xon/XenForo-SimpleForms#8]
An important bug report in Simple Form v2.1.8, XenForo 1.5.5

I have a form with a field that require users to enter an email address, and then in the Destination I have set **Destination Type: E-mail**. And in the **Options** tab I have set **Sender Email: {$fields.user_email.value}**

But when a user submit the form with his email address, the form is not being sent by user's email, it is sent by site's email. and it also forward and error in the server error log.

`**Error Info**
ErrorException: Undefined index: email_format - library/LiquidPro/SimpleForms/DataWriter/FormDestination.php:150

**Stack Trace**
#0 /home/nginx/domains/x/public/library/LiquidPro/SimpleForms/DataWriter/FormDestination.php(150): XenForo_Application::handlePhpError(8, 'Undefined index...', '/home/nginx/dom...', 150, Array)
#1 /home/nginx/domains/x/public/library/LiquidPro/SimpleForms/ControllerAdmin/FormDestination.php(154): LiquidPro_SimpleForms_DataWriter_FormDestination->setDestinationOptions(Array, Array)
#2 /home/nginx/domains/x/public/library/XenForo/FrontController.php(351): LiquidPro_SimpleForms_ControllerAdmin_FormDestination->actionSave()
#3 /home/nginx/domains/x/public/library/XenForo/FrontController.php(134): XenForo_FrontController->dispatch(Object(XenForo_RouteMatch))
#4 /home/nginx/domains/x/public/admin.php(13): XenForo_FrontController->run()
#5 {main}

**Request State**
array(3) {
  ["url"] => string(70) "http://www.forum.com/admin.php?form-destinations/save&form_id=16"
  ["_GET"] => array(2) {
    ["form-destinations/save"] => string(0) ""
    ["form_id"] => string(2) "16"
  }
  ["_POST"] => array(9) {
    ["name"] => string(0) ""
    ["destination_options"] => array(4) {
      ["email_subject_template"] => string(0) ""
      ["email_sender_email"] => string(0) ""
      ["email_recipient_email"] => string(0) ""
      ["email_message_template"] => string(0) ""
    }
    ["destination_options_shown"] => array(7) {
      [0] => string(22) "email_subject_template"
      [1] => string(18) "email_sender_email"
      [2] => string(21) "email_recipient_email"
      [3] => string(12) "email_format"
      [4] => string(22) "email_message_template"
      [5] => string(23) "email_hide_empty_fields"
      [6] => string(24) "email_enable_attachments"
    }
    ["form_id"] => string(2) "16"
    ["destination_id"] => string(1) "3"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(32) "/admin.php?form-destinations/add"
    ["_xfNoRedirect"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
`

Thanks

**Comment by Xon** [comment]
@VeerPrince without a indepth look, I expect you'll need to set a Recipient email address too.

Otherwise, this add-on may not allow the sender email address to be set like that. I'll have a look within the next week or two at it.
